[build]
  publish = "_site"
  # Allows overriding metadata.json via env var
  command = "[ \"$METADATA_JSON\" ] && echo $METADATA_JSON > _data/metadata.json; npm run build; make build"
  functions = "functions"
[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/llcranmer/toulbox"
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[headers]]
  for = "*.avif"
    [headers.values]
      Content-Type = "image/avif"
      Content-Disposition = "inline"
